# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='has_completed',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='member',
        ),
    ]
